name: connectVPN
on:
  workflow_dispatch:
jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: Write VPN Files
        run: |
          mkdir -p $HOME/.github/vpn
          echo "--daemon" > $HOME/.github/vpn/vpn.ovpn
          wget -O $HOME/.github/vpn/vpn.ovpn ${{ secrets.OPENVPN_CONFIG_LINK }}
          ls -al $HOME/.github/vpn/vpn.ovpn
      - name: Install openvpn3
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo wget -O /etc/apt/trusted.gpg.d/openvpn3.gpg https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          echo "deb https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/openvpn3.list
          sudo apt-get update
          sudo apt-get install -y openvpn3
      - name: VPN Connect
        run: |
          ls -al $HOME/.github/vpn
          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" | sudo openvpn3 session-start --config $HOME/.github/vpn/vpn.ovpn
          sleep 120
          curl icanhazip.com
      - name: Kill VPN Connection
        run: |
          sudo pkill openvpn
